<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;


class ForumChannel extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'forum_channels';
    protected $fillable = ['title', 'max_users'];

    public function save(array $options = []): bool
    {
        if (auth()->check()) {
            $this->created_by = auth()->user()->id;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function messages(): HasMany
    {
        return $this->hasMany(ForumChannelMessage::class, 'channel_id');
    }
}
