<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;


class ForumChannelMessage extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $table = 'forum_channel_messages';
    protected $fillable = ['message', 'channel_id', 'created_by'];

    public function save(array $options = []): bool
    {
        if (auth()->check()) {
            $this->created_by = auth()->user()->id;
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function channel(): BelongsTo
    {
        return $this->belongsTo(ForumChannel::class, 'channel_id');
    }
}
