<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class ForumChannel extends Model
{
    use SoftDeletes;

    protected $table = 'forum_channels';
    protected $fillable = ['title', 'max_users'];

    public function save(array $options = []): bool
    {
        $this->created_by = auth()->user()->id;
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
