<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class ForumChannelMessage extends Model
{
    use SoftDeletes;
    protected $table = 'forum_channel_messages';
    protected $fillable = ['content', 'channel_id', 'created_by'];

    public function save(array $options = []): bool
    {
        $this->created_by = auth()->user()->id;
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
